[project]
name = "eco-token"
description = "A simple token contract for waste management system"
authors = []
telemetry = true
cache_dir = "./.clarinet"

[contracts.eco-token]
path = "contracts/simple-token.clar"
clarity_version = 2
epoch = 2.4

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
